[package]
name = "waymaker-cli"
version = "0.2.1"
authors = ["Squirreljetpack"]
categories = ["command-line-utilities"]
edition = "2024"
exclude = ["assets/completions", "assets/presets"]
homepage = "https://github.com/Squirreljetpack/matchmaker"
keywords = ["fuzzy", "finder", "tui", "nucleo", "fzf"]
license = "MIT"
repository = "https://github.com/Squirreljetpack/matchmaker"
description = "Command-line interface for the waymaker fuzzy finder"

[package.metadata.dist]
dist = true
name = "waymaker"
display-name = "waymaker"
features = ["experimental"]
formula = "waymaker"
npm-package = "waymaker"

[package.metadata.wix]
upgrade-guid = "97859E79-FF52-4C64-9626-FE7E0FDA78E4"
path-guid = "1BEFEDD3-26B2-471B-8196-2BCF87E28476"
license = false
eula = false

[dependencies]
cli_boilerplate_automation = { workspace = true, features = ["serde", "bring"] }
waymaker-lib = { workspace = true, features = ["partial"] }
waymaker-partial = { workspace = true }
waymaker-partial-macros = { workspace = true }

ansi-to-tui = "8.0.0"
anyhow = "1.0"
clap = { version = "4.5.51", features = ["derive"] }
crokey = "1.3.0"
dirs = "6.0.0"
easy-ext = "1.0.3"
env_logger = "0.11.8"
glob = "0.3"
indexmap = { version = "2.12.0", features = ["serde"] }
log = "0.4"
mimalloc = { version = "0.1.48", features = ["v3"] }
regex = "1"
ratatui = { version = "0.30", features = ["serde"] }
serde = "1.0"
termimad = "0.34.1"
thiserror = "2.0"
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "macros", "sync", "time", "process", "signal", "net"] }
toml = "0.9.8"
which = "7.0.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[build-dependencies]
clap = { version = "4.0", features = ["derive"] }
clap_complete = "4.5"
strum = { version = "0.27.2", features = ["strum_macros"] }
strum_macros = "0.27.2"
thiserror = "2.0.17"

[[bin]]
name = "wm"
path = "src/main.rs"

[lints]
workspace = true

[features]
default = ["frizbee"]
frizbee = ["waymaker-lib/frizbee"]
experimental = [
  "waymaker-lib/experimental",
  # "log/max_level_debug"
]
