[ui.nav]
active = true
bar = "Plain"
color = "Cyan"

[tui]
percentage = 80
min = 10
max = 100

[preview]
show = true
wrap = true

[preview.border]
sides = "LEFT"
color = "Darkgray"
title_fg = "Cyan"

[previewer]
debounce_ms = 15
delay_clear = true

[[preview.layout]]
command = "if [ -f {2} ]; then cp {2} ~/.config/hypr/animations.lua 2>/dev/null && hyprctl reload >/dev/null 2>&1; bat --paging=never --style=header,grid,numbers --color=always -l lua {2} 2>/dev/null || cat {2}; fi"
side = "right"
percentage = 65

[columns]
split = "\t"
names = [
  "label",
  { name = "path", hidden = true }
]

[start.command]
cmd = '''
ANIM_DIR="$HOME/.config/hypr/animations"
for file in $ANIM_DIR/*.lua; do
  [ -f "$file" ] || continue
  read -r title < "$file" || true
  title="${title#--}"
  title="${title#\#}"
  title="${title# }"
  [ -z "$title" ] && title="${file##*/}"
  printf "%s\t%s\n" "$title" "$file"
done
'''

[query]
prompt = " Hyprland Animations > "

[start]
mode = "nav"

[binds]
"ctrl-j" = "Down"
"ctrl-k" = "Up"
"nav^^g" = "Pos(0)"
"nav^^G" = "Pos(-1)"
"nav^^q" = "Quit"
"nav^^esc" = "Quit"
"nav^^enter" = "Accept"
