[ui.nav]
active = true
bar = "Plain"
color = "Magenta"

[tui]
percentage = 20 # height
min = 15
max = 85

[footer]
content = " {magenta,bold:[Enter]} {darkgray:Salvar}  •  {cyan,bold:[j/k | ↓/↑]} {darkgray:Estilo}  •  {yellow,bold:[h/l | ←/→]} {darkgray:Velocidade}  •  {blue,bold:[r]} {darkgray:Girar Ângulo}  •  {darkgray,bold:[Esc / q]} {darkgray:Cancelar}"
row_connection = "Full"
match_indent = false
separator = "light"

[preview]
show = true
wrap = false

[preview.border]
sides = "LEFT"
color = "Darkgray"
title_fg = "Cyan"

[previewer]
debounce_ms = 10
delay_clear = false

[[preview.layout]]
command = "hypr-border-preview {2}"
side = "right"
percentage = 55

[columns]
split = "\t"
names = [
  "label",
  { name = "path", hidden = true }
]

[start.command]
cmd = '''
BORDERS_DIR="$HOME/.config/hypr/borders"
for file in $BORDERS_DIR/*.lua.tpl; do
  [ -f "$file" ] || continue
  read -r title < "$file" || true
  title="${title#--}"
  title="${title#\#}"
  title="${title# }"
  [ -z "$title" ] && title="${file##*/}"
  printf "%s\t%s\n" "$title" "$file"
done
'''

[query]
prompt = ">"
status_inline = true

[start]
mode = "nav"

[binds]
# Standard / query mode navigation & actions
"ctrl-j" = "Down"
"ctrl-k" = "Up"
"up" = "Up"
"down" = "Down"
"right" = "Transform(hypr-border-control speed_up {2})"
"left" = "Transform(hypr-border-control speed_down {2})"
"l" = "Transform(hypr-border-control speed_up {2})"
"h" = "Transform(hypr-border-control speed_down {2})"
"+" = "Transform(hypr-border-control speed_up {2})"
"=" = "Transform(hypr-border-control speed_up {2})"
"-" = "Transform(hypr-border-control speed_down {2})"
"r" = "Transform(hypr-border-control rotate_angle {2})"

# Nav Mode Binds (active when mode = "nav")
"nav^^j" = "Down"
"nav^^k" = "Up"
"nav^^up" = "Up"
"nav^^down" = "Down"
"nav^^g" = "Pos(0)"
"nav^^G" = "Pos(-1)"
"nav^^h" = "Transform(hypr-border-control speed_down {2})"
"nav^^l" = "Transform(hypr-border-control speed_up {2})"
"nav^^left" = "Transform(hypr-border-control speed_down {2})"
"nav^^right" = "Transform(hypr-border-control speed_up {2})"
"nav^^r" = "Transform(hypr-border-control rotate_angle {2})"
"nav^^+" = "Transform(hypr-border-control speed_up {2})"
"nav^^=" = "Transform(hypr-border-control speed_up {2})"
"nav^^-" = "Transform(hypr-border-control speed_down {2})"
"nav^^q" = "Quit"
"nav^^esc" = "Quit"
"nav^^enter" = "Accept"
