[tui]
percentage = 70
min = 15

[ui.nav]
active = true
bar = "Plain"
color = "black"

[query]
status_inline = true
cursor = "none"
prompt = "> "
prompt_style.fg = "Cyan"
prompt_style.modifier = "BOLD"

[results]
max = 15
icons = true

[results.symlink]
active = true

[matcher.sort]
threshold = "smart"

[matcher.frecency]
active = true

[preview]
show = true
wrap = true
scroll_wrap = true

[preview.media]
active = true
fit = "fit"

[previewer]
debounce_ms = 20
delay_clear = true

[preview.border]
sides = "LEFT"
color = "Darkgray"

[[preview.layout]]
side = "right"
percentage = 65
min = 25

[start]
directory = "~/Downloads"

[binds]
"ctrl-l" = "@look"
"alt-=" = "ExpandPreview(5)"
"alt-hyphen" = "ShrinkPreview(5)"
"ctrl-/" = "CyclePreview"
