[ui.nav]
active = true
basic = true
bar = "Plain"
color = "Darkgray"
prompt = ""
focus_on_start = "filter"
hints = false

[start]
sort = false
ansi = true

[start.command]
command = "wm session list --icons | grep -Ev '(_lazygitrs|_popups|[[:space:]]+\\.)'"
additional = [
    "wm session list --icons | grep -Ev '(_lazygitrs|_popups|[[:space:]]+\\.)'",
    "wm session list -t --icons | grep -Ev '(_lazygitrs|_popups|[[:space:]]+\\.)'",
    "wm session list -z --icons",
]

[tui]
percentage = 100
max = 9999

[matcher.sort]
threshold = false

[ui.border]
sides = ""

[query]
prompt = "⚡ "
status_inline = true

[query.local]
prompt = "⚡ "
prompt_style.fg = "cyan"

[query.frecency]
prompt = " "
prompt_style.fg = "blue"

[query.bookmarks]
prompt = " "
prompt_style.fg = "yellow"

[footer]
content = " {cyan,bold:[Enter]} {darkgray:Connect}  •  {magenta,bold:[Ctrl+S]} {darkgray:Windows}  •  {yellow,bold:[Tab]} {darkgray:Cycle}  •  {red,bold:[Ctrl+D]} {darkgray:Kill}  •  {blue,bold:[Esc]} {darkgray:Cancel}"
row_connection = "Full"
match_indent = false

[results]
spinner_inline = true
current_prefix = " "
unselected_prefix = "  "
row_connection = "Disjoint"
column_spacing = 1

[results.border]
sides = ""

[previewer]
debounce_ms = 20
delay_clear = true

[preview]
wrap = false

[preview.border]
sides = "LEFT"
color = "Darkgray"

[[preview.layout]]
command = 'wm session preview {=}'
side = "right"
percentage = 55

[ui.nav.binds]
"tab"           = "@reloadnext"
"shift-tab"     = "@reloadprev"
"backtab"       = "@reloadprev"
"shift-backtab" = "@reloadprev"
"s"             = ["Print(__SWITCH_WINDOW__)", "Quit"]
"S"             = ["Print(__SWITCH_WINDOW__)", "Quit"]
"ctrl-s"        = ["Print(__SWITCH_WINDOW__)", "Quit"]
"d"             = [ 'ExecuteAsync(wm session kill "{=}")', "SetQuery()", "Reload" ]
"D"             = [ 'ExecuteAsync(wm session kill "{=}")', "SetQuery()", "Reload" ]
"ctrl-d"        = [ 'ExecuteAsync(wm session kill "{=}")', "SetQuery()", "Reload" ]
","             = []

[binds]
"tab"           = "@reloadnext"
"shift-tab"     = "@reloadprev"
"backtab"       = "@reloadprev"
"shift-backtab" = "@reloadprev"
"ctrl-s"        = ["Print(__SWITCH_WINDOW__)", "Quit"]
"ctrl-d"        = [ 'ExecuteAsync(wm session kill "{=}")', "SetQuery()", "Reload" ]
","             = []
